export const enum ErrorCode {

    // Authentication
    AUTHENTICATION_FAILED = 'AUTHENTICATION_FAILED',
    USER_NOT_FOUND = 'USER_NOT_FOUND',
    INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
    NOT_AUTHORIZED = 'NOT_AUTHORIZED',
    NOT_AUTHENTICATED = 'NOT_AUTHENTICATED',

    // Database
    RECORD_NOT_FOUND = 'RECORD_NOT_FOUND',
    RECORD_ALREADY_EXISTS = 'RECORD_ALREADY_EXISTS',
    REQUEST_REJECTED = 'REQUEST_REJECTED',

    // Misc.
    UNKNOWN_ERROR = 'UNKNOWN_ERROR',
    INVALID_PAYLOAD = 'INVALID_PAYLOAD',
    INTERNAL_ERROR = 'INTERNAL_ERROR',

}
