export enum AuthenticationErrorCode {
    AUTHENTICATION_FAILED = 'AUTHENTICATION_FAILED',
    USER_NOT_FOUND = 'USER_NOT_FOUND',
    INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
    NOT_AUTHORIZED = 'NOT_AUTHORIZED',
}

export enum DatabaseServiceErrorCode {
    UNKNOWN_ERROR = 'UNKNOWN_ERROR',
    RECORD_NOT_FOUND = 'RECORD_NOT_FOUND',
}
